FROM node:18

# Install Java (required for Firebase emulators)
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/*

# Install Firebase tools
RUN npm install -g firebase-tools

WORKDIR /app
COPY firebase.json .
COPY firestore.rules .
COPY firestore.indexes.json .
COPY firebase-start.sh /app/firebase-start.sh

# Ports for Firebase emulators
EXPOSE 9099
EXPOSE 9090
EXPOSE 4000

CMD ["/app/firebase-start.sh"]
